name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java Development Kit (JDK)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c

      - name: Install Host Qt (Desktop Linux)
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.2'
          target: 'desktop'
          setup-python: 'false'

      - name: Install Target Qt (Android ARM64)
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.2'
          target: 'android'
          arch: 'android_arm64_v8a'
          setup-python: 'false'

      - name: Build Qt Android APK
        run: |
          mkdir build
          cd build
          qt-cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release -DQT_HOST_PATH=$Qt6_DIR
          ninja

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Radharani-App-APK
          path: build/android-build/build/outputs/apk/release/*.apk
